// Code generated by pyffi-gen. DO NOT EDIT.
// Source: Python module "claude_agent_sdk"

package sdk

import (
	"fmt"

	"github.com/i2y/pyffi"
)

// Module wraps the Python "claude_agent_sdk" module.
type Module struct {
	rt  *pyffi.Runtime
	mod *pyffi.Object
}

// New imports the "claude_agent_sdk" module and returns a typed wrapper.
func New(rt *pyffi.Runtime) (*Module, error) {
	mod, err := rt.Import("claude_agent_sdk")
	if err != nil {
		return nil, err
	}
	return &Module{rt: rt, mod: mod}, nil
}

// Close releases the module reference.
func (m *Module) Close() error {
	return m.mod.Close()
}

// ensure fmt is used
var _ = fmt.Errorf

// CanUseTool wraps claude_agent_sdk.CanUseTool.
func (m *Module) CanUseTool() (any, error) {
	fn := m.mod.Attr("CanUseTool")
	if fn == nil {
		return nil, fmt.Errorf("CanUseTool not found")
	}
	defer fn.Close()
	result, err := fn.Call()
	if err != nil {
		return nil, err
	}
	defer result.Close()
	return result.GoValue()
}

// HookCallback wraps claude_agent_sdk.HookCallback.
func (m *Module) HookCallback() (any, error) {
	fn := m.mod.Attr("HookCallback")
	if fn == nil {
		return nil, fmt.Errorf("HookCallback not found")
	}
	defer fn.Close()
	result, err := fn.Call()
	if err != nil {
		return nil, err
	}
	defer result.Close()
	return result.GoValue()
}

// McpServerConnectionStatus wraps claude_agent_sdk.McpServerConnectionStatus.
func (m *Module) McpServerConnectionStatus() (any, error) {
	fn := m.mod.Attr("McpServerConnectionStatus")
	if fn == nil {
		return nil, fmt.Errorf("McpServerConnectionStatus not found")
	}
	defer fn.Close()
	result, err := fn.Call()
	if err != nil {
		return nil, err
	}
	defer result.Close()
	return result.GoValue()
}

// PermissionMode wraps claude_agent_sdk.PermissionMode.
func (m *Module) PermissionMode() (any, error) {
	fn := m.mod.Attr("PermissionMode")
	if fn == nil {
		return nil, fmt.Errorf("PermissionMode not found")
	}
	defer fn.Close()
	result, err := fn.Call()
	if err != nil {
		return nil, err
	}
	defer result.Close()
	return result.GoValue()
}

// RateLimitStatus wraps claude_agent_sdk.RateLimitStatus.
func (m *Module) RateLimitStatus() (any, error) {
	fn := m.mod.Attr("RateLimitStatus")
	if fn == nil {
		return nil, fmt.Errorf("RateLimitStatus not found")
	}
	defer fn.Close()
	result, err := fn.Call()
	if err != nil {
		return nil, err
	}
	defer result.Close()
	return result.GoValue()
}

// RateLimitType wraps claude_agent_sdk.RateLimitType.
func (m *Module) RateLimitType() (any, error) {
	fn := m.mod.Attr("RateLimitType")
	if fn == nil {
		return nil, fmt.Errorf("RateLimitType not found")
	}
	defer fn.Close()
	result, err := fn.Call()
	if err != nil {
		return nil, err
	}
	defer result.Close()
	return result.GoValue()
}

// SdkBeta wraps claude_agent_sdk.SdkBeta.
func (m *Module) SdkBeta() (any, error) {
	fn := m.mod.Attr("SdkBeta")
	if fn == nil {
		return nil, fmt.Errorf("SdkBeta not found")
	}
	defer fn.Close()
	result, err := fn.Call()
	if err != nil {
		return nil, err
	}
	defer result.Close()
	return result.GoValue()
}

// SettingSource wraps claude_agent_sdk.SettingSource.
func (m *Module) SettingSource() (any, error) {
	fn := m.mod.Attr("SettingSource")
	if fn == nil {
		return nil, fmt.Errorf("SettingSource not found")
	}
	defer fn.Close()
	result, err := fn.Call()
	if err != nil {
		return nil, err
	}
	defer result.Close()
	return result.GoValue()
}

// TaskNotificationStatus wraps claude_agent_sdk.TaskNotificationStatus.
func (m *Module) TaskNotificationStatus() (any, error) {
	fn := m.mod.Attr("TaskNotificationStatus")
	if fn == nil {
		return nil, fmt.Errorf("TaskNotificationStatus not found")
	}
	defer fn.Close()
	result, err := fn.Call()
	if err != nil {
		return nil, err
	}
	defer result.Close()
	return result.GoValue()
}

// CreateSdkMcpServer wraps claude_agent_sdk.create_sdk_mcp_server.
// Create an in-process MCP server that runs within your Python application.
func (m *Module) CreateSdkMcpServer(name string, opts ...pyffi.KW) (*McpSdkServerConfig, error) {
	fn := m.mod.Attr("create_sdk_mcp_server")
	if fn == nil {
		return nil, fmt.Errorf("create_sdk_mcp_server not found")
	}
	defer fn.Close()
	args := []any{name}
	var kw pyffi.KW
	if len(opts) > 0 {
		kw = opts[0]
	}
	result, err := fn.CallKw(args, kw)
	if err != nil {
		return nil, err
	}
	return &McpSdkServerConfig{obj: result, rt: m.rt}, nil
}

// Dataclass wraps claude_agent_sdk.dataclass.
// Add dunder methods based on the fields defined in the class.
func (m *Module) Dataclass(opts ...pyffi.KW) (any, error) {
	fn := m.mod.Attr("dataclass")
	if fn == nil {
		return nil, fmt.Errorf("dataclass not found")
	}
	defer fn.Close()
	args := []any{}
	var kw pyffi.KW
	if len(opts) > 0 {
		kw = opts[0]
	}
	result, err := fn.CallKw(args, kw)
	if err != nil {
		return nil, err
	}
	defer result.Close()
	return result.GoValue()
}

// GetSessionInfo wraps claude_agent_sdk.get_session_info.
// Reads metadata for a single session by ID.
func (m *Module) GetSessionInfo(sessionId string, opts ...pyffi.KW) (*SDKSessionInfo, error) {
	fn := m.mod.Attr("get_session_info")
	if fn == nil {
		return nil, fmt.Errorf("get_session_info not found")
	}
	defer fn.Close()
	args := []any{sessionId}
	var kw pyffi.KW
	if len(opts) > 0 {
		kw = opts[0]
	}
	result, err := fn.CallKw(args, kw)
	if err != nil {
		return nil, err
	}
	return &SDKSessionInfo{obj: result, rt: m.rt}, nil
}

// GetSessionMessages wraps claude_agent_sdk.get_session_messages.
// Reads a session's conversation messages from its JSONL transcript file.
func (m *Module) GetSessionMessages(sessionId string, opts ...pyffi.KW) (any, error) {
	fn := m.mod.Attr("get_session_messages")
	if fn == nil {
		return nil, fmt.Errorf("get_session_messages not found")
	}
	defer fn.Close()
	args := []any{sessionId}
	var kw pyffi.KW
	if len(opts) > 0 {
		kw = opts[0]
	}
	result, err := fn.CallKw(args, kw)
	if err != nil {
		return nil, err
	}
	defer result.Close()
	return result.GoValue()
}

// ListSessions wraps claude_agent_sdk.list_sessions.
// Lists sessions with metadata extracted from stat + head/tail reads.
func (m *Module) ListSessions(opts ...pyffi.KW) (any, error) {
	fn := m.mod.Attr("list_sessions")
	if fn == nil {
		return nil, fmt.Errorf("list_sessions not found")
	}
	defer fn.Close()
	args := []any{}
	var kw pyffi.KW
	if len(opts) > 0 {
		kw = opts[0]
	}
	result, err := fn.CallKw(args, kw)
	if err != nil {
		return nil, err
	}
	defer result.Close()
	return result.GoValue()
}

// Query wraps claude_agent_sdk.query.
// Query Claude Code for one-shot or unidirectional streaming interactions.
func (m *Module) Query(opts ...pyffi.KW) (any, error) {
	fn := m.mod.Attr("query")
	if fn == nil {
		return nil, fmt.Errorf("query not found")
	}
	defer fn.Close()
	args := []any{}
	var kw pyffi.KW
	if len(opts) > 0 {
		kw = opts[0]
	}
	result, err := fn.CallKw(args, kw)
	if err != nil {
		return nil, err
	}
	defer result.Close()
	return result.GoValue()
}

// RenameSession wraps claude_agent_sdk.rename_session.
// Rename a session by appending a custom-title entry.
func (m *Module) RenameSession(sessionId string, title string, opts ...pyffi.KW) error {
	fn := m.mod.Attr("rename_session")
	if fn == nil {
		return fmt.Errorf("rename_session not found")
	}
	defer fn.Close()
	args := []any{sessionId, title}
	var kw pyffi.KW
	if len(opts) > 0 {
		kw = opts[0]
	}
	result, err := fn.CallKw(args, kw)
	if err != nil {
		return err
	}
	result.Close()
	return nil
}

// TagSession wraps claude_agent_sdk.tag_session.
// Tag a session. Pass “None“ to clear the tag.
func (m *Module) TagSession(sessionId string, tag any, opts ...pyffi.KW) error {
	fn := m.mod.Attr("tag_session")
	if fn == nil {
		return fmt.Errorf("tag_session not found")
	}
	defer fn.Close()
	args := []any{sessionId, tag}
	var kw pyffi.KW
	if len(opts) > 0 {
		kw = opts[0]
	}
	result, err := fn.CallKw(args, kw)
	if err != nil {
		return err
	}
	result.Close()
	return nil
}

// Tool wraps claude_agent_sdk.tool.
// Decorator for defining MCP tools with type safety.
func (m *Module) Tool(name string, description string, inputSchema any, opts ...pyffi.KW) (any, error) {
	fn := m.mod.Attr("tool")
	if fn == nil {
		return nil, fmt.Errorf("tool not found")
	}
	defer fn.Close()
	args := []any{name, description, inputSchema}
	var kw pyffi.KW
	if len(opts) > 0 {
		kw = opts[0]
	}
	result, err := fn.CallKw(args, kw)
	if err != nil {
		return nil, err
	}
	defer result.Close()
	return result.GoValue()
}

// AgentDefinition wraps a Python AgentDefinition instance.
// Agent definition configuration.
type AgentDefinition struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewAgentDefinition creates a new AgentDefinition instance.
func (m *Module) NewAgentDefinition(description string, prompt string, tools any, model any, skills any, memory any, mcpServers any) (*AgentDefinition, error) {
	cls := m.mod.Attr("AgentDefinition")
	if cls == nil {
		return nil, fmt.Errorf("class AgentDefinition not found")
	}
	defer cls.Close()
	obj, err := cls.Call(description, prompt, tools, model, skills, memory, mcpServers)
	if err != nil {
		return nil, err
	}
	return &AgentDefinition{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *AgentDefinition) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *AgentDefinition) Object() *pyffi.Object {
	return w.obj
}

// Any wraps a Python Any instance.
// Special type indicating an unconstrained type.
type Any struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewAny creates a new Any instance.
func (m *Module) NewAny() (*Any, error) {
	cls := m.mod.Attr("Any")
	if cls == nil {
		return nil, fmt.Errorf("class Any not found")
	}
	defer cls.Close()
	obj, err := cls.Call()
	if err != nil {
		return nil, err
	}
	return &Any{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *Any) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *Any) Object() *pyffi.Object {
	return w.obj
}

// AssistantMessage wraps a Python AssistantMessage instance.
// Assistant message with content blocks.
type AssistantMessage struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewAssistantMessage creates a new AssistantMessage instance.
func (m *Module) NewAssistantMessage(content any, model string, parentToolUseId any, error any, usage any) (*AssistantMessage, error) {
	cls := m.mod.Attr("AssistantMessage")
	if cls == nil {
		return nil, fmt.Errorf("class AssistantMessage not found")
	}
	defer cls.Close()
	obj, err := cls.Call(content, model, parentToolUseId, error, usage)
	if err != nil {
		return nil, err
	}
	return &AssistantMessage{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *AssistantMessage) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *AssistantMessage) Object() *pyffi.Object {
	return w.obj
}

// Awaitable wraps a Python Awaitable instance.
type Awaitable struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewAwaitable creates a new Awaitable instance.
func (m *Module) NewAwaitable() (*Awaitable, error) {
	cls := m.mod.Attr("Awaitable")
	if cls == nil {
		return nil, fmt.Errorf("class Awaitable not found")
	}
	defer cls.Close()
	obj, err := cls.Call()
	if err != nil {
		return nil, err
	}
	return &Awaitable{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *Awaitable) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *Awaitable) Object() *pyffi.Object {
	return w.obj
}

// BaseHookInput wraps a Python BaseHookInput instance.
// Base hook input fields present across many hook events.
type BaseHookInput struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewBaseHookInput creates a new BaseHookInput instance.
func (m *Module) NewBaseHookInput() (*BaseHookInput, error) {
	cls := m.mod.Attr("BaseHookInput")
	if cls == nil {
		return nil, fmt.Errorf("class BaseHookInput not found")
	}
	defer cls.Close()
	obj, err := cls.Call()
	if err != nil {
		return nil, err
	}
	return &BaseHookInput{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *BaseHookInput) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *BaseHookInput) Object() *pyffi.Object {
	return w.obj
}

// CLIConnectionError wraps a Python CLIConnectionError instance.
// Raised when unable to connect to Claude Code.
type CLIConnectionError struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewCLIConnectionError creates a new CLIConnectionError instance.
func (m *Module) NewCLIConnectionError() (*CLIConnectionError, error) {
	cls := m.mod.Attr("CLIConnectionError")
	if cls == nil {
		return nil, fmt.Errorf("class CLIConnectionError not found")
	}
	defer cls.Close()
	obj, err := cls.Call()
	if err != nil {
		return nil, err
	}
	return &CLIConnectionError{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *CLIConnectionError) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *CLIConnectionError) Object() *pyffi.Object {
	return w.obj
}

// CLIJSONDecodeError wraps a Python CLIJSONDecodeError instance.
// Raised when unable to decode JSON from CLI output.
type CLIJSONDecodeError struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewCLIJSONDecodeError creates a new CLIJSONDecodeError instance.
func (m *Module) NewCLIJSONDecodeError(line string, originalError any) (*CLIJSONDecodeError, error) {
	cls := m.mod.Attr("CLIJSONDecodeError")
	if cls == nil {
		return nil, fmt.Errorf("class CLIJSONDecodeError not found")
	}
	defer cls.Close()
	obj, err := cls.Call(line, originalError)
	if err != nil {
		return nil, err
	}
	return &CLIJSONDecodeError{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *CLIJSONDecodeError) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *CLIJSONDecodeError) Object() *pyffi.Object {
	return w.obj
}

// CLINotFoundError wraps a Python CLINotFoundError instance.
// Raised when Claude Code is not found or not installed.
type CLINotFoundError struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewCLINotFoundError creates a new CLINotFoundError instance.
func (m *Module) NewCLINotFoundError(message string, cliPath any) (*CLINotFoundError, error) {
	cls := m.mod.Attr("CLINotFoundError")
	if cls == nil {
		return nil, fmt.Errorf("class CLINotFoundError not found")
	}
	defer cls.Close()
	obj, err := cls.Call(message, cliPath)
	if err != nil {
		return nil, err
	}
	return &CLINotFoundError{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *CLINotFoundError) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *CLINotFoundError) Object() *pyffi.Object {
	return w.obj
}

// Callable wraps a Python Callable instance.
type Callable struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewCallable creates a new Callable instance.
func (m *Module) NewCallable() (*Callable, error) {
	cls := m.mod.Attr("Callable")
	if cls == nil {
		return nil, fmt.Errorf("class Callable not found")
	}
	defer cls.Close()
	obj, err := cls.Call()
	if err != nil {
		return nil, err
	}
	return &Callable{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *Callable) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *Callable) Object() *pyffi.Object {
	return w.obj
}

// ClaudeAgentOptions wraps a Python ClaudeAgentOptions instance.
// Query options for Claude SDK.
type ClaudeAgentOptions struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewClaudeAgentOptions creates a new ClaudeAgentOptions instance.
func (m *Module) NewClaudeAgentOptions(tools any, allowedTools any, systemPrompt any, mcpServers any, permissionMode any, continueConversation bool, resume any, maxTurns any, maxBudgetUsd any, disallowedTools any, model any, fallbackModel any, betas any, permissionPromptToolName any, cwd any, cliPath any, settings any, addDirs any, env any, extraArgs any, maxBufferSize any, debugStderr any, stderr any, canUseTool any, hooks any, user any, includePartialMessages bool, forkSession bool, agents any, settingSources any, sandbox *SandboxSettings, plugins any, maxThinkingTokens any, thinking any, effort any, outputFormat any, enableFileCheckpointing bool) (*ClaudeAgentOptions, error) {
	cls := m.mod.Attr("ClaudeAgentOptions")
	if cls == nil {
		return nil, fmt.Errorf("class ClaudeAgentOptions not found")
	}
	defer cls.Close()
	obj, err := cls.Call(tools, allowedTools, systemPrompt, mcpServers, permissionMode, continueConversation, resume, maxTurns, maxBudgetUsd, disallowedTools, model, fallbackModel, betas, permissionPromptToolName, cwd, cliPath, settings, addDirs, env, extraArgs, maxBufferSize, debugStderr, stderr, canUseTool, hooks, user, includePartialMessages, forkSession, agents, settingSources, sandbox, plugins, maxThinkingTokens, thinking, effort, outputFormat, enableFileCheckpointing)
	if err != nil {
		return nil, err
	}
	return &ClaudeAgentOptions{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *ClaudeAgentOptions) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *ClaudeAgentOptions) Object() *pyffi.Object {
	return w.obj
}

// ClaudeSDKClient wraps a Python ClaudeSDKClient instance.
// Client for bidirectional, interactive conversations with Claude Code.
type ClaudeSDKClient struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewClaudeSDKClient creates a new ClaudeSDKClient instance.
func (m *Module) NewClaudeSDKClient(options *ClaudeAgentOptions, transport *Transport) (*ClaudeSDKClient, error) {
	cls := m.mod.Attr("ClaudeSDKClient")
	if cls == nil {
		return nil, fmt.Errorf("class ClaudeSDKClient not found")
	}
	defer cls.Close()
	obj, err := cls.Call(options, transport)
	if err != nil {
		return nil, err
	}
	return &ClaudeSDKClient{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *ClaudeSDKClient) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *ClaudeSDKClient) Object() *pyffi.Object {
	return w.obj
}

// Connect wraps ClaudeSDKClient.connect.
// Connect to Claude with a prompt or message stream.
func (w *ClaudeSDKClient) Connect(prompt any) error {
	fn := w.obj.Attr("connect")
	if fn == nil {
		return fmt.Errorf("connect not found")
	}
	defer fn.Close()
	result, err := fn.Call(prompt)
	if err != nil {
		return err
	}
	result.Close()
	return nil
}

// Disconnect wraps ClaudeSDKClient.disconnect.
// Disconnect from Claude.
func (w *ClaudeSDKClient) Disconnect() error {
	fn := w.obj.Attr("disconnect")
	if fn == nil {
		return fmt.Errorf("disconnect not found")
	}
	defer fn.Close()
	result, err := fn.Call()
	if err != nil {
		return err
	}
	result.Close()
	return nil
}

// GetMcpStatus wraps ClaudeSDKClient.get_mcp_status.
// Get current MCP server connection status (only works with streaming mode).
func (w *ClaudeSDKClient) GetMcpStatus() (*McpStatusResponse, error) {
	fn := w.obj.Attr("get_mcp_status")
	if fn == nil {
		return nil, fmt.Errorf("get_mcp_status not found")
	}
	defer fn.Close()
	result, err := fn.Call()
	if err != nil {
		return nil, err
	}
	return &McpStatusResponse{obj: result, rt: w.rt}, nil
}

// GetServerInfo wraps ClaudeSDKClient.get_server_info.
// Get server initialization info including available commands and output styles.
func (w *ClaudeSDKClient) GetServerInfo() (any, error) {
	fn := w.obj.Attr("get_server_info")
	if fn == nil {
		return nil, fmt.Errorf("get_server_info not found")
	}
	defer fn.Close()
	result, err := fn.Call()
	if err != nil {
		return nil, err
	}
	defer result.Close()
	return result.GoValue()
}

// Interrupt wraps ClaudeSDKClient.interrupt.
// Send interrupt signal (only works with streaming mode).
func (w *ClaudeSDKClient) Interrupt() error {
	fn := w.obj.Attr("interrupt")
	if fn == nil {
		return fmt.Errorf("interrupt not found")
	}
	defer fn.Close()
	result, err := fn.Call()
	if err != nil {
		return err
	}
	result.Close()
	return nil
}

// Query wraps ClaudeSDKClient.query.
// Send a new request in streaming mode.
func (w *ClaudeSDKClient) Query(prompt any, sessionId string) error {
	fn := w.obj.Attr("query")
	if fn == nil {
		return fmt.Errorf("query not found")
	}
	defer fn.Close()
	result, err := fn.Call(prompt, sessionId)
	if err != nil {
		return err
	}
	result.Close()
	return nil
}

// ReceiveMessages wraps ClaudeSDKClient.receive_messages.
// Receive all messages from Claude.
func (w *ClaudeSDKClient) ReceiveMessages() (any, error) {
	fn := w.obj.Attr("receive_messages")
	if fn == nil {
		return nil, fmt.Errorf("receive_messages not found")
	}
	defer fn.Close()
	result, err := fn.Call()
	if err != nil {
		return nil, err
	}
	defer result.Close()
	return result.GoValue()
}

// ReceiveResponse wraps ClaudeSDKClient.receive_response.
// Receive messages from Claude until and including a ResultMessage.
func (w *ClaudeSDKClient) ReceiveResponse() (any, error) {
	fn := w.obj.Attr("receive_response")
	if fn == nil {
		return nil, fmt.Errorf("receive_response not found")
	}
	defer fn.Close()
	result, err := fn.Call()
	if err != nil {
		return nil, err
	}
	defer result.Close()
	return result.GoValue()
}

// ReconnectMcpServer wraps ClaudeSDKClient.reconnect_mcp_server.
// Reconnect a disconnected or failed MCP server (only works with streaming mode).
func (w *ClaudeSDKClient) ReconnectMcpServer(serverName string) error {
	fn := w.obj.Attr("reconnect_mcp_server")
	if fn == nil {
		return fmt.Errorf("reconnect_mcp_server not found")
	}
	defer fn.Close()
	result, err := fn.Call(serverName)
	if err != nil {
		return err
	}
	result.Close()
	return nil
}

// RewindFiles wraps ClaudeSDKClient.rewind_files.
// Rewind tracked files to their state at a specific user message.
func (w *ClaudeSDKClient) RewindFiles(userMessageId string) error {
	fn := w.obj.Attr("rewind_files")
	if fn == nil {
		return fmt.Errorf("rewind_files not found")
	}
	defer fn.Close()
	result, err := fn.Call(userMessageId)
	if err != nil {
		return err
	}
	result.Close()
	return nil
}

// SetModel wraps ClaudeSDKClient.set_model.
// Change the AI model during conversation (only works with streaming mode).
func (w *ClaudeSDKClient) SetModel(model any) error {
	fn := w.obj.Attr("set_model")
	if fn == nil {
		return fmt.Errorf("set_model not found")
	}
	defer fn.Close()
	result, err := fn.Call(model)
	if err != nil {
		return err
	}
	result.Close()
	return nil
}

// SetPermissionMode wraps ClaudeSDKClient.set_permission_mode.
// Change permission mode during conversation (only works with streaming mode).
func (w *ClaudeSDKClient) SetPermissionMode(mode string) error {
	fn := w.obj.Attr("set_permission_mode")
	if fn == nil {
		return fmt.Errorf("set_permission_mode not found")
	}
	defer fn.Close()
	result, err := fn.Call(mode)
	if err != nil {
		return err
	}
	result.Close()
	return nil
}

// StopTask wraps ClaudeSDKClient.stop_task.
// Stop a running task (only works with streaming mode).
func (w *ClaudeSDKClient) StopTask(taskId string) error {
	fn := w.obj.Attr("stop_task")
	if fn == nil {
		return fmt.Errorf("stop_task not found")
	}
	defer fn.Close()
	result, err := fn.Call(taskId)
	if err != nil {
		return err
	}
	result.Close()
	return nil
}

// ToggleMcpServer wraps ClaudeSDKClient.toggle_mcp_server.
// Enable or disable an MCP server (only works with streaming mode).
func (w *ClaudeSDKClient) ToggleMcpServer(serverName string, enabled bool) error {
	fn := w.obj.Attr("toggle_mcp_server")
	if fn == nil {
		return fmt.Errorf("toggle_mcp_server not found")
	}
	defer fn.Close()
	result, err := fn.Call(serverName, enabled)
	if err != nil {
		return err
	}
	result.Close()
	return nil
}

// ClaudeSDKError wraps a Python ClaudeSDKError instance.
// Base exception for all Claude SDK errors.
type ClaudeSDKError struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewClaudeSDKError creates a new ClaudeSDKError instance.
func (m *Module) NewClaudeSDKError() (*ClaudeSDKError, error) {
	cls := m.mod.Attr("ClaudeSDKError")
	if cls == nil {
		return nil, fmt.Errorf("class ClaudeSDKError not found")
	}
	defer cls.Close()
	obj, err := cls.Call()
	if err != nil {
		return nil, err
	}
	return &ClaudeSDKError{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *ClaudeSDKError) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *ClaudeSDKError) Object() *pyffi.Object {
	return w.obj
}

// Generic wraps a Python Generic instance.
// Abstract base class for generic types.
type Generic struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewGeneric creates a new Generic instance.
func (m *Module) NewGeneric() (*Generic, error) {
	cls := m.mod.Attr("Generic")
	if cls == nil {
		return nil, fmt.Errorf("class Generic not found")
	}
	defer cls.Close()
	obj, err := cls.Call()
	if err != nil {
		return nil, err
	}
	return &Generic{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *Generic) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *Generic) Object() *pyffi.Object {
	return w.obj
}

// HookContext wraps a Python HookContext instance.
// Context information for hook callbacks.
type HookContext struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewHookContext creates a new HookContext instance.
func (m *Module) NewHookContext() (*HookContext, error) {
	cls := m.mod.Attr("HookContext")
	if cls == nil {
		return nil, fmt.Errorf("class HookContext not found")
	}
	defer cls.Close()
	obj, err := cls.Call()
	if err != nil {
		return nil, err
	}
	return &HookContext{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *HookContext) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *HookContext) Object() *pyffi.Object {
	return w.obj
}

// HookMatcher wraps a Python HookMatcher instance.
// Hook matcher configuration.
type HookMatcher struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewHookMatcher creates a new HookMatcher instance.
func (m *Module) NewHookMatcher(matcher any, hooks any, timeout any) (*HookMatcher, error) {
	cls := m.mod.Attr("HookMatcher")
	if cls == nil {
		return nil, fmt.Errorf("class HookMatcher not found")
	}
	defer cls.Close()
	obj, err := cls.Call(matcher, hooks, timeout)
	if err != nil {
		return nil, err
	}
	return &HookMatcher{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *HookMatcher) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *HookMatcher) Object() *pyffi.Object {
	return w.obj
}

// McpSdkServerConfig wraps a Python McpSdkServerConfig instance.
// SDK MCP server configuration.
type McpSdkServerConfig struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewMcpSdkServerConfig creates a new McpSdkServerConfig instance.
func (m *Module) NewMcpSdkServerConfig() (*McpSdkServerConfig, error) {
	cls := m.mod.Attr("McpSdkServerConfig")
	if cls == nil {
		return nil, fmt.Errorf("class McpSdkServerConfig not found")
	}
	defer cls.Close()
	obj, err := cls.Call()
	if err != nil {
		return nil, err
	}
	return &McpSdkServerConfig{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *McpSdkServerConfig) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *McpSdkServerConfig) Object() *pyffi.Object {
	return w.obj
}

// McpServerInfo wraps a Python McpServerInfo instance.
// Server info from MCP initialize handshake (available when connected).
type McpServerInfo struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewMcpServerInfo creates a new McpServerInfo instance.
func (m *Module) NewMcpServerInfo() (*McpServerInfo, error) {
	cls := m.mod.Attr("McpServerInfo")
	if cls == nil {
		return nil, fmt.Errorf("class McpServerInfo not found")
	}
	defer cls.Close()
	obj, err := cls.Call()
	if err != nil {
		return nil, err
	}
	return &McpServerInfo{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *McpServerInfo) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *McpServerInfo) Object() *pyffi.Object {
	return w.obj
}

// McpServerStatus wraps a Python McpServerStatus instance.
// Status information for an MCP server connection.
type McpServerStatus struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewMcpServerStatus creates a new McpServerStatus instance.
func (m *Module) NewMcpServerStatus() (*McpServerStatus, error) {
	cls := m.mod.Attr("McpServerStatus")
	if cls == nil {
		return nil, fmt.Errorf("class McpServerStatus not found")
	}
	defer cls.Close()
	obj, err := cls.Call()
	if err != nil {
		return nil, err
	}
	return &McpServerStatus{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *McpServerStatus) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *McpServerStatus) Object() *pyffi.Object {
	return w.obj
}

// McpStatusResponse wraps a Python McpStatusResponse instance.
// Response from `ClaudeSDKClient.get_mcp_status()`.
type McpStatusResponse struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewMcpStatusResponse creates a new McpStatusResponse instance.
func (m *Module) NewMcpStatusResponse() (*McpStatusResponse, error) {
	cls := m.mod.Attr("McpStatusResponse")
	if cls == nil {
		return nil, fmt.Errorf("class McpStatusResponse not found")
	}
	defer cls.Close()
	obj, err := cls.Call()
	if err != nil {
		return nil, err
	}
	return &McpStatusResponse{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *McpStatusResponse) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *McpStatusResponse) Object() *pyffi.Object {
	return w.obj
}

// McpToolAnnotations wraps a Python McpToolAnnotations instance.
// Tool annotations as returned in MCP server status.
type McpToolAnnotations struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewMcpToolAnnotations creates a new McpToolAnnotations instance.
func (m *Module) NewMcpToolAnnotations() (*McpToolAnnotations, error) {
	cls := m.mod.Attr("McpToolAnnotations")
	if cls == nil {
		return nil, fmt.Errorf("class McpToolAnnotations not found")
	}
	defer cls.Close()
	obj, err := cls.Call()
	if err != nil {
		return nil, err
	}
	return &McpToolAnnotations{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *McpToolAnnotations) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *McpToolAnnotations) Object() *pyffi.Object {
	return w.obj
}

// McpToolInfo wraps a Python McpToolInfo instance.
// Information about a tool provided by an MCP server.
type McpToolInfo struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewMcpToolInfo creates a new McpToolInfo instance.
func (m *Module) NewMcpToolInfo() (*McpToolInfo, error) {
	cls := m.mod.Attr("McpToolInfo")
	if cls == nil {
		return nil, fmt.Errorf("class McpToolInfo not found")
	}
	defer cls.Close()
	obj, err := cls.Call()
	if err != nil {
		return nil, err
	}
	return &McpToolInfo{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *McpToolInfo) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *McpToolInfo) Object() *pyffi.Object {
	return w.obj
}

// NotificationHookInput wraps a Python NotificationHookInput instance.
// Input data for Notification hook events.
type NotificationHookInput struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewNotificationHookInput creates a new NotificationHookInput instance.
func (m *Module) NewNotificationHookInput() (*NotificationHookInput, error) {
	cls := m.mod.Attr("NotificationHookInput")
	if cls == nil {
		return nil, fmt.Errorf("class NotificationHookInput not found")
	}
	defer cls.Close()
	obj, err := cls.Call()
	if err != nil {
		return nil, err
	}
	return &NotificationHookInput{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *NotificationHookInput) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *NotificationHookInput) Object() *pyffi.Object {
	return w.obj
}

// NotificationHookSpecificOutput wraps a Python NotificationHookSpecificOutput instance.
// Hook-specific output for Notification events.
type NotificationHookSpecificOutput struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewNotificationHookSpecificOutput creates a new NotificationHookSpecificOutput instance.
func (m *Module) NewNotificationHookSpecificOutput() (*NotificationHookSpecificOutput, error) {
	cls := m.mod.Attr("NotificationHookSpecificOutput")
	if cls == nil {
		return nil, fmt.Errorf("class NotificationHookSpecificOutput not found")
	}
	defer cls.Close()
	obj, err := cls.Call()
	if err != nil {
		return nil, err
	}
	return &NotificationHookSpecificOutput{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *NotificationHookSpecificOutput) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *NotificationHookSpecificOutput) Object() *pyffi.Object {
	return w.obj
}

// PermissionRequestHookInput wraps a Python PermissionRequestHookInput instance.
// Input data for PermissionRequest hook events.
type PermissionRequestHookInput struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewPermissionRequestHookInput creates a new PermissionRequestHookInput instance.
func (m *Module) NewPermissionRequestHookInput() (*PermissionRequestHookInput, error) {
	cls := m.mod.Attr("PermissionRequestHookInput")
	if cls == nil {
		return nil, fmt.Errorf("class PermissionRequestHookInput not found")
	}
	defer cls.Close()
	obj, err := cls.Call()
	if err != nil {
		return nil, err
	}
	return &PermissionRequestHookInput{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *PermissionRequestHookInput) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *PermissionRequestHookInput) Object() *pyffi.Object {
	return w.obj
}

// PermissionRequestHookSpecificOutput wraps a Python PermissionRequestHookSpecificOutput instance.
// Hook-specific output for PermissionRequest events.
type PermissionRequestHookSpecificOutput struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewPermissionRequestHookSpecificOutput creates a new PermissionRequestHookSpecificOutput instance.
func (m *Module) NewPermissionRequestHookSpecificOutput() (*PermissionRequestHookSpecificOutput, error) {
	cls := m.mod.Attr("PermissionRequestHookSpecificOutput")
	if cls == nil {
		return nil, fmt.Errorf("class PermissionRequestHookSpecificOutput not found")
	}
	defer cls.Close()
	obj, err := cls.Call()
	if err != nil {
		return nil, err
	}
	return &PermissionRequestHookSpecificOutput{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *PermissionRequestHookSpecificOutput) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *PermissionRequestHookSpecificOutput) Object() *pyffi.Object {
	return w.obj
}

// PermissionResultAllow wraps a Python PermissionResultAllow instance.
// Allow permission result.
type PermissionResultAllow struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewPermissionResultAllow creates a new PermissionResultAllow instance.
func (m *Module) NewPermissionResultAllow(behavior any, updatedInput any, updatedPermissions any) (*PermissionResultAllow, error) {
	cls := m.mod.Attr("PermissionResultAllow")
	if cls == nil {
		return nil, fmt.Errorf("class PermissionResultAllow not found")
	}
	defer cls.Close()
	obj, err := cls.Call(behavior, updatedInput, updatedPermissions)
	if err != nil {
		return nil, err
	}
	return &PermissionResultAllow{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *PermissionResultAllow) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *PermissionResultAllow) Object() *pyffi.Object {
	return w.obj
}

// PermissionResultDeny wraps a Python PermissionResultDeny instance.
// Deny permission result.
type PermissionResultDeny struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewPermissionResultDeny creates a new PermissionResultDeny instance.
func (m *Module) NewPermissionResultDeny(behavior any, message string, interrupt bool) (*PermissionResultDeny, error) {
	cls := m.mod.Attr("PermissionResultDeny")
	if cls == nil {
		return nil, fmt.Errorf("class PermissionResultDeny not found")
	}
	defer cls.Close()
	obj, err := cls.Call(behavior, message, interrupt)
	if err != nil {
		return nil, err
	}
	return &PermissionResultDeny{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *PermissionResultDeny) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *PermissionResultDeny) Object() *pyffi.Object {
	return w.obj
}

// PermissionUpdate wraps a Python PermissionUpdate instance.
// Permission update configuration.
type PermissionUpdate struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewPermissionUpdate creates a new PermissionUpdate instance.
func (m *Module) NewPermissionUpdate(type_ any, rules any, behavior any, mode any, directories any, destination any) (*PermissionUpdate, error) {
	cls := m.mod.Attr("PermissionUpdate")
	if cls == nil {
		return nil, fmt.Errorf("class PermissionUpdate not found")
	}
	defer cls.Close()
	obj, err := cls.Call(type_, rules, behavior, mode, directories, destination)
	if err != nil {
		return nil, err
	}
	return &PermissionUpdate{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *PermissionUpdate) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *PermissionUpdate) Object() *pyffi.Object {
	return w.obj
}

// ToDict wraps PermissionUpdate.to_dict.
// Convert PermissionUpdate to dictionary format matching TypeScript control protocol.
func (w *PermissionUpdate) ToDict() (any, error) {
	fn := w.obj.Attr("to_dict")
	if fn == nil {
		return nil, fmt.Errorf("to_dict not found")
	}
	defer fn.Close()
	result, err := fn.Call()
	if err != nil {
		return nil, err
	}
	defer result.Close()
	return result.GoValue()
}

// PostToolUseFailureHookInput wraps a Python PostToolUseFailureHookInput instance.
// Input data for PostToolUseFailure hook events.
type PostToolUseFailureHookInput struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewPostToolUseFailureHookInput creates a new PostToolUseFailureHookInput instance.
func (m *Module) NewPostToolUseFailureHookInput() (*PostToolUseFailureHookInput, error) {
	cls := m.mod.Attr("PostToolUseFailureHookInput")
	if cls == nil {
		return nil, fmt.Errorf("class PostToolUseFailureHookInput not found")
	}
	defer cls.Close()
	obj, err := cls.Call()
	if err != nil {
		return nil, err
	}
	return &PostToolUseFailureHookInput{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *PostToolUseFailureHookInput) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *PostToolUseFailureHookInput) Object() *pyffi.Object {
	return w.obj
}

// PostToolUseFailureHookSpecificOutput wraps a Python PostToolUseFailureHookSpecificOutput instance.
// Hook-specific output for PostToolUseFailure events.
type PostToolUseFailureHookSpecificOutput struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewPostToolUseFailureHookSpecificOutput creates a new PostToolUseFailureHookSpecificOutput instance.
func (m *Module) NewPostToolUseFailureHookSpecificOutput() (*PostToolUseFailureHookSpecificOutput, error) {
	cls := m.mod.Attr("PostToolUseFailureHookSpecificOutput")
	if cls == nil {
		return nil, fmt.Errorf("class PostToolUseFailureHookSpecificOutput not found")
	}
	defer cls.Close()
	obj, err := cls.Call()
	if err != nil {
		return nil, err
	}
	return &PostToolUseFailureHookSpecificOutput{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *PostToolUseFailureHookSpecificOutput) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *PostToolUseFailureHookSpecificOutput) Object() *pyffi.Object {
	return w.obj
}

// PostToolUseHookInput wraps a Python PostToolUseHookInput instance.
// Input data for PostToolUse hook events.
type PostToolUseHookInput struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewPostToolUseHookInput creates a new PostToolUseHookInput instance.
func (m *Module) NewPostToolUseHookInput() (*PostToolUseHookInput, error) {
	cls := m.mod.Attr("PostToolUseHookInput")
	if cls == nil {
		return nil, fmt.Errorf("class PostToolUseHookInput not found")
	}
	defer cls.Close()
	obj, err := cls.Call()
	if err != nil {
		return nil, err
	}
	return &PostToolUseHookInput{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *PostToolUseHookInput) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *PostToolUseHookInput) Object() *pyffi.Object {
	return w.obj
}

// PreCompactHookInput wraps a Python PreCompactHookInput instance.
// Input data for PreCompact hook events.
type PreCompactHookInput struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewPreCompactHookInput creates a new PreCompactHookInput instance.
func (m *Module) NewPreCompactHookInput() (*PreCompactHookInput, error) {
	cls := m.mod.Attr("PreCompactHookInput")
	if cls == nil {
		return nil, fmt.Errorf("class PreCompactHookInput not found")
	}
	defer cls.Close()
	obj, err := cls.Call()
	if err != nil {
		return nil, err
	}
	return &PreCompactHookInput{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *PreCompactHookInput) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *PreCompactHookInput) Object() *pyffi.Object {
	return w.obj
}

// PreToolUseHookInput wraps a Python PreToolUseHookInput instance.
// Input data for PreToolUse hook events.
type PreToolUseHookInput struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewPreToolUseHookInput creates a new PreToolUseHookInput instance.
func (m *Module) NewPreToolUseHookInput() (*PreToolUseHookInput, error) {
	cls := m.mod.Attr("PreToolUseHookInput")
	if cls == nil {
		return nil, fmt.Errorf("class PreToolUseHookInput not found")
	}
	defer cls.Close()
	obj, err := cls.Call()
	if err != nil {
		return nil, err
	}
	return &PreToolUseHookInput{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *PreToolUseHookInput) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *PreToolUseHookInput) Object() *pyffi.Object {
	return w.obj
}

// ProcessError wraps a Python ProcessError instance.
// Raised when the CLI process fails.
type ProcessError struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewProcessError creates a new ProcessError instance.
func (m *Module) NewProcessError(message string, exitCode any, stderr any) (*ProcessError, error) {
	cls := m.mod.Attr("ProcessError")
	if cls == nil {
		return nil, fmt.Errorf("class ProcessError not found")
	}
	defer cls.Close()
	obj, err := cls.Call(message, exitCode, stderr)
	if err != nil {
		return nil, err
	}
	return &ProcessError{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *ProcessError) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *ProcessError) Object() *pyffi.Object {
	return w.obj
}

// RateLimitEvent wraps a Python RateLimitEvent instance.
// Rate limit event emitted when rate limit info changes.
type RateLimitEvent struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewRateLimitEvent creates a new RateLimitEvent instance.
func (m *Module) NewRateLimitEvent(rateLimitInfo *RateLimitInfo, uuid string, sessionId string) (*RateLimitEvent, error) {
	cls := m.mod.Attr("RateLimitEvent")
	if cls == nil {
		return nil, fmt.Errorf("class RateLimitEvent not found")
	}
	defer cls.Close()
	obj, err := cls.Call(rateLimitInfo, uuid, sessionId)
	if err != nil {
		return nil, err
	}
	return &RateLimitEvent{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *RateLimitEvent) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *RateLimitEvent) Object() *pyffi.Object {
	return w.obj
}

// RateLimitInfo wraps a Python RateLimitInfo instance.
// Rate limit status emitted by the CLI when rate limit state changes.
type RateLimitInfo struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewRateLimitInfo creates a new RateLimitInfo instance.
func (m *Module) NewRateLimitInfo(status any, resetsAt any, rateLimitType any, utilization any, overageStatus any, overageResetsAt any, overageDisabledReason any, raw any) (*RateLimitInfo, error) {
	cls := m.mod.Attr("RateLimitInfo")
	if cls == nil {
		return nil, fmt.Errorf("class RateLimitInfo not found")
	}
	defer cls.Close()
	obj, err := cls.Call(status, resetsAt, rateLimitType, utilization, overageStatus, overageResetsAt, overageDisabledReason, raw)
	if err != nil {
		return nil, err
	}
	return &RateLimitInfo{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *RateLimitInfo) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *RateLimitInfo) Object() *pyffi.Object {
	return w.obj
}

// ResultMessage wraps a Python ResultMessage instance.
// Result message with cost and usage information.
type ResultMessage struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewResultMessage creates a new ResultMessage instance.
func (m *Module) NewResultMessage(subtype string, durationMs int64, durationApiMs int64, isError bool, numTurns int64, sessionId string, stopReason any, totalCostUsd any, usage any, result any, structuredOutput any) (*ResultMessage, error) {
	cls := m.mod.Attr("ResultMessage")
	if cls == nil {
		return nil, fmt.Errorf("class ResultMessage not found")
	}
	defer cls.Close()
	obj, err := cls.Call(subtype, durationMs, durationApiMs, isError, numTurns, sessionId, stopReason, totalCostUsd, usage, result, structuredOutput)
	if err != nil {
		return nil, err
	}
	return &ResultMessage{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *ResultMessage) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *ResultMessage) Object() *pyffi.Object {
	return w.obj
}

// SDKSessionInfo wraps a Python SDKSessionInfo instance.
// Session metadata returned by “list_sessions()“.
type SDKSessionInfo struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewSDKSessionInfo creates a new SDKSessionInfo instance.
func (m *Module) NewSDKSessionInfo(sessionId string, summary string, lastModified int64, fileSize any, customTitle any, firstPrompt any, gitBranch any, cwd any, tag any, createdAt any) (*SDKSessionInfo, error) {
	cls := m.mod.Attr("SDKSessionInfo")
	if cls == nil {
		return nil, fmt.Errorf("class SDKSessionInfo not found")
	}
	defer cls.Close()
	obj, err := cls.Call(sessionId, summary, lastModified, fileSize, customTitle, firstPrompt, gitBranch, cwd, tag, createdAt)
	if err != nil {
		return nil, err
	}
	return &SDKSessionInfo{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *SDKSessionInfo) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *SDKSessionInfo) Object() *pyffi.Object {
	return w.obj
}

// SandboxIgnoreViolations wraps a Python SandboxIgnoreViolations instance.
// Violations to ignore in sandbox.
type SandboxIgnoreViolations struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewSandboxIgnoreViolations creates a new SandboxIgnoreViolations instance.
func (m *Module) NewSandboxIgnoreViolations() (*SandboxIgnoreViolations, error) {
	cls := m.mod.Attr("SandboxIgnoreViolations")
	if cls == nil {
		return nil, fmt.Errorf("class SandboxIgnoreViolations not found")
	}
	defer cls.Close()
	obj, err := cls.Call()
	if err != nil {
		return nil, err
	}
	return &SandboxIgnoreViolations{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *SandboxIgnoreViolations) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *SandboxIgnoreViolations) Object() *pyffi.Object {
	return w.obj
}

// SandboxNetworkConfig wraps a Python SandboxNetworkConfig instance.
// Network configuration for sandbox.
type SandboxNetworkConfig struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewSandboxNetworkConfig creates a new SandboxNetworkConfig instance.
func (m *Module) NewSandboxNetworkConfig() (*SandboxNetworkConfig, error) {
	cls := m.mod.Attr("SandboxNetworkConfig")
	if cls == nil {
		return nil, fmt.Errorf("class SandboxNetworkConfig not found")
	}
	defer cls.Close()
	obj, err := cls.Call()
	if err != nil {
		return nil, err
	}
	return &SandboxNetworkConfig{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *SandboxNetworkConfig) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *SandboxNetworkConfig) Object() *pyffi.Object {
	return w.obj
}

// SandboxSettings wraps a Python SandboxSettings instance.
// Sandbox settings configuration.
type SandboxSettings struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewSandboxSettings creates a new SandboxSettings instance.
func (m *Module) NewSandboxSettings() (*SandboxSettings, error) {
	cls := m.mod.Attr("SandboxSettings")
	if cls == nil {
		return nil, fmt.Errorf("class SandboxSettings not found")
	}
	defer cls.Close()
	obj, err := cls.Call()
	if err != nil {
		return nil, err
	}
	return &SandboxSettings{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *SandboxSettings) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *SandboxSettings) Object() *pyffi.Object {
	return w.obj
}

// SdkMcpTool wraps a Python SdkMcpTool instance.
// Definition for an SDK MCP tool.
type SdkMcpTool struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewSdkMcpTool creates a new SdkMcpTool instance.
func (m *Module) NewSdkMcpTool(name string, description string, inputSchema any, handler any, annotations *ToolAnnotations) (*SdkMcpTool, error) {
	cls := m.mod.Attr("SdkMcpTool")
	if cls == nil {
		return nil, fmt.Errorf("class SdkMcpTool not found")
	}
	defer cls.Close()
	obj, err := cls.Call(name, description, inputSchema, handler, annotations)
	if err != nil {
		return nil, err
	}
	return &SdkMcpTool{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *SdkMcpTool) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *SdkMcpTool) Object() *pyffi.Object {
	return w.obj
}

// SdkPluginConfig wraps a Python SdkPluginConfig instance.
// SDK plugin configuration.
type SdkPluginConfig struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewSdkPluginConfig creates a new SdkPluginConfig instance.
func (m *Module) NewSdkPluginConfig() (*SdkPluginConfig, error) {
	cls := m.mod.Attr("SdkPluginConfig")
	if cls == nil {
		return nil, fmt.Errorf("class SdkPluginConfig not found")
	}
	defer cls.Close()
	obj, err := cls.Call()
	if err != nil {
		return nil, err
	}
	return &SdkPluginConfig{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *SdkPluginConfig) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *SdkPluginConfig) Object() *pyffi.Object {
	return w.obj
}

// SessionMessage wraps a Python SessionMessage instance.
// A user or assistant message from a session transcript.
type SessionMessage struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewSessionMessage creates a new SessionMessage instance.
func (m *Module) NewSessionMessage(type_ any, uuid string, sessionId string, message any, parentToolUseId any) (*SessionMessage, error) {
	cls := m.mod.Attr("SessionMessage")
	if cls == nil {
		return nil, fmt.Errorf("class SessionMessage not found")
	}
	defer cls.Close()
	obj, err := cls.Call(type_, uuid, sessionId, message, parentToolUseId)
	if err != nil {
		return nil, err
	}
	return &SessionMessage{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *SessionMessage) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *SessionMessage) Object() *pyffi.Object {
	return w.obj
}

// StopHookInput wraps a Python StopHookInput instance.
// Input data for Stop hook events.
type StopHookInput struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewStopHookInput creates a new StopHookInput instance.
func (m *Module) NewStopHookInput() (*StopHookInput, error) {
	cls := m.mod.Attr("StopHookInput")
	if cls == nil {
		return nil, fmt.Errorf("class StopHookInput not found")
	}
	defer cls.Close()
	obj, err := cls.Call()
	if err != nil {
		return nil, err
	}
	return &StopHookInput{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *StopHookInput) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *StopHookInput) Object() *pyffi.Object {
	return w.obj
}

// StreamEvent wraps a Python StreamEvent instance.
// Stream event for partial message updates during streaming.
type StreamEvent struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewStreamEvent creates a new StreamEvent instance.
func (m *Module) NewStreamEvent(uuid string, sessionId string, event any, parentToolUseId any) (*StreamEvent, error) {
	cls := m.mod.Attr("StreamEvent")
	if cls == nil {
		return nil, fmt.Errorf("class StreamEvent not found")
	}
	defer cls.Close()
	obj, err := cls.Call(uuid, sessionId, event, parentToolUseId)
	if err != nil {
		return nil, err
	}
	return &StreamEvent{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *StreamEvent) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *StreamEvent) Object() *pyffi.Object {
	return w.obj
}

// SubagentStartHookInput wraps a Python SubagentStartHookInput instance.
// Input data for SubagentStart hook events.
type SubagentStartHookInput struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewSubagentStartHookInput creates a new SubagentStartHookInput instance.
func (m *Module) NewSubagentStartHookInput() (*SubagentStartHookInput, error) {
	cls := m.mod.Attr("SubagentStartHookInput")
	if cls == nil {
		return nil, fmt.Errorf("class SubagentStartHookInput not found")
	}
	defer cls.Close()
	obj, err := cls.Call()
	if err != nil {
		return nil, err
	}
	return &SubagentStartHookInput{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *SubagentStartHookInput) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *SubagentStartHookInput) Object() *pyffi.Object {
	return w.obj
}

// SubagentStartHookSpecificOutput wraps a Python SubagentStartHookSpecificOutput instance.
// Hook-specific output for SubagentStart events.
type SubagentStartHookSpecificOutput struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewSubagentStartHookSpecificOutput creates a new SubagentStartHookSpecificOutput instance.
func (m *Module) NewSubagentStartHookSpecificOutput() (*SubagentStartHookSpecificOutput, error) {
	cls := m.mod.Attr("SubagentStartHookSpecificOutput")
	if cls == nil {
		return nil, fmt.Errorf("class SubagentStartHookSpecificOutput not found")
	}
	defer cls.Close()
	obj, err := cls.Call()
	if err != nil {
		return nil, err
	}
	return &SubagentStartHookSpecificOutput{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *SubagentStartHookSpecificOutput) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *SubagentStartHookSpecificOutput) Object() *pyffi.Object {
	return w.obj
}

// SubagentStopHookInput wraps a Python SubagentStopHookInput instance.
// Input data for SubagentStop hook events.
type SubagentStopHookInput struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewSubagentStopHookInput creates a new SubagentStopHookInput instance.
func (m *Module) NewSubagentStopHookInput() (*SubagentStopHookInput, error) {
	cls := m.mod.Attr("SubagentStopHookInput")
	if cls == nil {
		return nil, fmt.Errorf("class SubagentStopHookInput not found")
	}
	defer cls.Close()
	obj, err := cls.Call()
	if err != nil {
		return nil, err
	}
	return &SubagentStopHookInput{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *SubagentStopHookInput) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *SubagentStopHookInput) Object() *pyffi.Object {
	return w.obj
}

// SystemMessage wraps a Python SystemMessage instance.
// System message with metadata.
type SystemMessage struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewSystemMessage creates a new SystemMessage instance.
func (m *Module) NewSystemMessage(subtype string, data any) (*SystemMessage, error) {
	cls := m.mod.Attr("SystemMessage")
	if cls == nil {
		return nil, fmt.Errorf("class SystemMessage not found")
	}
	defer cls.Close()
	obj, err := cls.Call(subtype, data)
	if err != nil {
		return nil, err
	}
	return &SystemMessage{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *SystemMessage) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *SystemMessage) Object() *pyffi.Object {
	return w.obj
}

// TaskNotificationMessage wraps a Python TaskNotificationMessage instance.
// System message emitted when a task completes, fails, or is stopped.
type TaskNotificationMessage struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewTaskNotificationMessage creates a new TaskNotificationMessage instance.
func (m *Module) NewTaskNotificationMessage(subtype string, data any, taskId string, status any, outputFile string, summary string, uuid string, sessionId string, toolUseId any, usage *TaskUsage) (*TaskNotificationMessage, error) {
	cls := m.mod.Attr("TaskNotificationMessage")
	if cls == nil {
		return nil, fmt.Errorf("class TaskNotificationMessage not found")
	}
	defer cls.Close()
	obj, err := cls.Call(subtype, data, taskId, status, outputFile, summary, uuid, sessionId, toolUseId, usage)
	if err != nil {
		return nil, err
	}
	return &TaskNotificationMessage{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *TaskNotificationMessage) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *TaskNotificationMessage) Object() *pyffi.Object {
	return w.obj
}

// TaskProgressMessage wraps a Python TaskProgressMessage instance.
// System message emitted while a task is in progress.
type TaskProgressMessage struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewTaskProgressMessage creates a new TaskProgressMessage instance.
func (m *Module) NewTaskProgressMessage(subtype string, data any, taskId string, description string, usage *TaskUsage, uuid string, sessionId string, toolUseId any, lastToolName any) (*TaskProgressMessage, error) {
	cls := m.mod.Attr("TaskProgressMessage")
	if cls == nil {
		return nil, fmt.Errorf("class TaskProgressMessage not found")
	}
	defer cls.Close()
	obj, err := cls.Call(subtype, data, taskId, description, usage, uuid, sessionId, toolUseId, lastToolName)
	if err != nil {
		return nil, err
	}
	return &TaskProgressMessage{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *TaskProgressMessage) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *TaskProgressMessage) Object() *pyffi.Object {
	return w.obj
}

// TaskStartedMessage wraps a Python TaskStartedMessage instance.
// System message emitted when a task starts.
type TaskStartedMessage struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewTaskStartedMessage creates a new TaskStartedMessage instance.
func (m *Module) NewTaskStartedMessage(subtype string, data any, taskId string, description string, uuid string, sessionId string, toolUseId any, taskType any) (*TaskStartedMessage, error) {
	cls := m.mod.Attr("TaskStartedMessage")
	if cls == nil {
		return nil, fmt.Errorf("class TaskStartedMessage not found")
	}
	defer cls.Close()
	obj, err := cls.Call(subtype, data, taskId, description, uuid, sessionId, toolUseId, taskType)
	if err != nil {
		return nil, err
	}
	return &TaskStartedMessage{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *TaskStartedMessage) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *TaskStartedMessage) Object() *pyffi.Object {
	return w.obj
}

// TaskUsage wraps a Python TaskUsage instance.
// Usage statistics reported in task_progress and task_notification messages.
type TaskUsage struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewTaskUsage creates a new TaskUsage instance.
func (m *Module) NewTaskUsage() (*TaskUsage, error) {
	cls := m.mod.Attr("TaskUsage")
	if cls == nil {
		return nil, fmt.Errorf("class TaskUsage not found")
	}
	defer cls.Close()
	obj, err := cls.Call()
	if err != nil {
		return nil, err
	}
	return &TaskUsage{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *TaskUsage) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *TaskUsage) Object() *pyffi.Object {
	return w.obj
}

// TextBlock wraps a Python TextBlock instance.
// Text content block.
type TextBlock struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewTextBlock creates a new TextBlock instance.
func (m *Module) NewTextBlock(text string) (*TextBlock, error) {
	cls := m.mod.Attr("TextBlock")
	if cls == nil {
		return nil, fmt.Errorf("class TextBlock not found")
	}
	defer cls.Close()
	obj, err := cls.Call(text)
	if err != nil {
		return nil, err
	}
	return &TextBlock{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *TextBlock) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *TextBlock) Object() *pyffi.Object {
	return w.obj
}

// ThinkingBlock wraps a Python ThinkingBlock instance.
// Thinking content block.
type ThinkingBlock struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewThinkingBlock creates a new ThinkingBlock instance.
func (m *Module) NewThinkingBlock(thinking string, signature string) (*ThinkingBlock, error) {
	cls := m.mod.Attr("ThinkingBlock")
	if cls == nil {
		return nil, fmt.Errorf("class ThinkingBlock not found")
	}
	defer cls.Close()
	obj, err := cls.Call(thinking, signature)
	if err != nil {
		return nil, err
	}
	return &ThinkingBlock{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *ThinkingBlock) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *ThinkingBlock) Object() *pyffi.Object {
	return w.obj
}

// ThinkingConfigAdaptive wraps a Python ThinkingConfigAdaptive instance.
// dict() -> new empty dictionary
type ThinkingConfigAdaptive struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewThinkingConfigAdaptive creates a new ThinkingConfigAdaptive instance.
func (m *Module) NewThinkingConfigAdaptive() (*ThinkingConfigAdaptive, error) {
	cls := m.mod.Attr("ThinkingConfigAdaptive")
	if cls == nil {
		return nil, fmt.Errorf("class ThinkingConfigAdaptive not found")
	}
	defer cls.Close()
	obj, err := cls.Call()
	if err != nil {
		return nil, err
	}
	return &ThinkingConfigAdaptive{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *ThinkingConfigAdaptive) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *ThinkingConfigAdaptive) Object() *pyffi.Object {
	return w.obj
}

// ThinkingConfigDisabled wraps a Python ThinkingConfigDisabled instance.
// dict() -> new empty dictionary
type ThinkingConfigDisabled struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewThinkingConfigDisabled creates a new ThinkingConfigDisabled instance.
func (m *Module) NewThinkingConfigDisabled() (*ThinkingConfigDisabled, error) {
	cls := m.mod.Attr("ThinkingConfigDisabled")
	if cls == nil {
		return nil, fmt.Errorf("class ThinkingConfigDisabled not found")
	}
	defer cls.Close()
	obj, err := cls.Call()
	if err != nil {
		return nil, err
	}
	return &ThinkingConfigDisabled{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *ThinkingConfigDisabled) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *ThinkingConfigDisabled) Object() *pyffi.Object {
	return w.obj
}

// ThinkingConfigEnabled wraps a Python ThinkingConfigEnabled instance.
// dict() -> new empty dictionary
type ThinkingConfigEnabled struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewThinkingConfigEnabled creates a new ThinkingConfigEnabled instance.
func (m *Module) NewThinkingConfigEnabled() (*ThinkingConfigEnabled, error) {
	cls := m.mod.Attr("ThinkingConfigEnabled")
	if cls == nil {
		return nil, fmt.Errorf("class ThinkingConfigEnabled not found")
	}
	defer cls.Close()
	obj, err := cls.Call()
	if err != nil {
		return nil, err
	}
	return &ThinkingConfigEnabled{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *ThinkingConfigEnabled) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *ThinkingConfigEnabled) Object() *pyffi.Object {
	return w.obj
}

// ToolAnnotations wraps a Python ToolAnnotations instance.
// Additional properties describing a Tool to clients.
type ToolAnnotations struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewToolAnnotations creates a new ToolAnnotations instance.
func (m *Module) NewToolAnnotations() (*ToolAnnotations, error) {
	cls := m.mod.Attr("ToolAnnotations")
	if cls == nil {
		return nil, fmt.Errorf("class ToolAnnotations not found")
	}
	defer cls.Close()
	obj, err := cls.Call()
	if err != nil {
		return nil, err
	}
	return &ToolAnnotations{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *ToolAnnotations) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *ToolAnnotations) Object() *pyffi.Object {
	return w.obj
}

// Copy wraps ToolAnnotations.copy.
// Returns a copy of the model.
func (w *ToolAnnotations) Copy(include any, exclude any, update any, deep bool) (any, error) {
	fn := w.obj.Attr("copy")
	if fn == nil {
		return nil, fmt.Errorf("copy not found")
	}
	defer fn.Close()
	result, err := fn.Call(include, exclude, update, deep)
	if err != nil {
		return nil, err
	}
	defer result.Close()
	return result.GoValue()
}

// Dict wraps ToolAnnotations.dict.
func (w *ToolAnnotations) Dict(include any, exclude any, byAlias bool, excludeUnset bool, excludeDefaults bool, excludeNone bool) (any, error) {
	fn := w.obj.Attr("dict")
	if fn == nil {
		return nil, fmt.Errorf("dict not found")
	}
	defer fn.Close()
	result, err := fn.Call(include, exclude, byAlias, excludeUnset, excludeDefaults, excludeNone)
	if err != nil {
		return nil, err
	}
	defer result.Close()
	return result.GoValue()
}

// Json wraps ToolAnnotations.json.
func (w *ToolAnnotations) Json(include any, exclude any, byAlias bool, excludeUnset bool, excludeDefaults bool, excludeNone bool, encoder any, modelsAsDict bool) (string, error) {
	fn := w.obj.Attr("json")
	if fn == nil {
		return "", fmt.Errorf("json not found")
	}
	defer fn.Close()
	result, err := fn.Call(include, exclude, byAlias, excludeUnset, excludeDefaults, excludeNone, encoder, modelsAsDict)
	if err != nil {
		return "", err
	}
	defer result.Close()
	return result.GoString()
}

// ModelCopy wraps ToolAnnotations.model_copy.
// !!! abstract "Usage Documentation"
func (w *ToolAnnotations) ModelCopy(update any, deep bool) (any, error) {
	fn := w.obj.Attr("model_copy")
	if fn == nil {
		return nil, fmt.Errorf("model_copy not found")
	}
	defer fn.Close()
	result, err := fn.Call(update, deep)
	if err != nil {
		return nil, err
	}
	defer result.Close()
	return result.GoValue()
}

// ModelDump wraps ToolAnnotations.model_dump.
// !!! abstract "Usage Documentation"
func (w *ToolAnnotations) ModelDump(mode any, include any, exclude any, context any, byAlias any, excludeUnset bool, excludeDefaults bool, excludeNone bool, excludeComputedFields bool, roundTrip bool, warnings any, fallback any, serializeAsAny bool) (any, error) {
	fn := w.obj.Attr("model_dump")
	if fn == nil {
		return nil, fmt.Errorf("model_dump not found")
	}
	defer fn.Close()
	result, err := fn.Call(mode, include, exclude, context, byAlias, excludeUnset, excludeDefaults, excludeNone, excludeComputedFields, roundTrip, warnings, fallback, serializeAsAny)
	if err != nil {
		return nil, err
	}
	defer result.Close()
	return result.GoValue()
}

// ModelDumpJson wraps ToolAnnotations.model_dump_json.
// !!! abstract "Usage Documentation"
func (w *ToolAnnotations) ModelDumpJson(indent any, ensureAscii bool, include any, exclude any, context any, byAlias any, excludeUnset bool, excludeDefaults bool, excludeNone bool, excludeComputedFields bool, roundTrip bool, warnings any, fallback any, serializeAsAny bool) (string, error) {
	fn := w.obj.Attr("model_dump_json")
	if fn == nil {
		return "", fmt.Errorf("model_dump_json not found")
	}
	defer fn.Close()
	result, err := fn.Call(indent, ensureAscii, include, exclude, context, byAlias, excludeUnset, excludeDefaults, excludeNone, excludeComputedFields, roundTrip, warnings, fallback, serializeAsAny)
	if err != nil {
		return "", err
	}
	defer result.Close()
	return result.GoString()
}

// ModelPostInit wraps ToolAnnotations.model_post_init.
// Override this method to perform additional initialization after `__init__` and `model_construct`.
func (w *ToolAnnotations) ModelPostInit(context any) error {
	fn := w.obj.Attr("model_post_init")
	if fn == nil {
		return fmt.Errorf("model_post_init not found")
	}
	defer fn.Close()
	result, err := fn.Call(context)
	if err != nil {
		return err
	}
	result.Close()
	return nil
}

// ToolPermissionContext wraps a Python ToolPermissionContext instance.
// Context information for tool permission callbacks.
type ToolPermissionContext struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewToolPermissionContext creates a new ToolPermissionContext instance.
func (m *Module) NewToolPermissionContext(signal any, suggestions any) (*ToolPermissionContext, error) {
	cls := m.mod.Attr("ToolPermissionContext")
	if cls == nil {
		return nil, fmt.Errorf("class ToolPermissionContext not found")
	}
	defer cls.Close()
	obj, err := cls.Call(signal, suggestions)
	if err != nil {
		return nil, err
	}
	return &ToolPermissionContext{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *ToolPermissionContext) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *ToolPermissionContext) Object() *pyffi.Object {
	return w.obj
}

// ToolResultBlock wraps a Python ToolResultBlock instance.
// Tool result content block.
type ToolResultBlock struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewToolResultBlock creates a new ToolResultBlock instance.
func (m *Module) NewToolResultBlock(toolUseId string, content any, isError any) (*ToolResultBlock, error) {
	cls := m.mod.Attr("ToolResultBlock")
	if cls == nil {
		return nil, fmt.Errorf("class ToolResultBlock not found")
	}
	defer cls.Close()
	obj, err := cls.Call(toolUseId, content, isError)
	if err != nil {
		return nil, err
	}
	return &ToolResultBlock{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *ToolResultBlock) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *ToolResultBlock) Object() *pyffi.Object {
	return w.obj
}

// ToolUseBlock wraps a Python ToolUseBlock instance.
// Tool use content block.
type ToolUseBlock struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewToolUseBlock creates a new ToolUseBlock instance.
func (m *Module) NewToolUseBlock(id string, name string, input any) (*ToolUseBlock, error) {
	cls := m.mod.Attr("ToolUseBlock")
	if cls == nil {
		return nil, fmt.Errorf("class ToolUseBlock not found")
	}
	defer cls.Close()
	obj, err := cls.Call(id, name, input)
	if err != nil {
		return nil, err
	}
	return &ToolUseBlock{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *ToolUseBlock) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *ToolUseBlock) Object() *pyffi.Object {
	return w.obj
}

// Transport wraps a Python Transport instance.
// Abstract transport for Claude communication.
type Transport struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewTransport creates a new Transport instance.
func (m *Module) NewTransport() (*Transport, error) {
	cls := m.mod.Attr("Transport")
	if cls == nil {
		return nil, fmt.Errorf("class Transport not found")
	}
	defer cls.Close()
	obj, err := cls.Call()
	if err != nil {
		return nil, err
	}
	return &Transport{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *Transport) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *Transport) Object() *pyffi.Object {
	return w.obj
}

// Connect wraps Transport.connect.
// Connect the transport and prepare for communication.
func (w *Transport) Connect() error {
	fn := w.obj.Attr("connect")
	if fn == nil {
		return fmt.Errorf("connect not found")
	}
	defer fn.Close()
	result, err := fn.Call()
	if err != nil {
		return err
	}
	result.Close()
	return nil
}

// EndInput wraps Transport.end_input.
// End the input stream (close stdin for process transports).
func (w *Transport) EndInput() error {
	fn := w.obj.Attr("end_input")
	if fn == nil {
		return fmt.Errorf("end_input not found")
	}
	defer fn.Close()
	result, err := fn.Call()
	if err != nil {
		return err
	}
	result.Close()
	return nil
}

// IsReady wraps Transport.is_ready.
// Check if transport is ready for communication.
func (w *Transport) IsReady() (bool, error) {
	fn := w.obj.Attr("is_ready")
	if fn == nil {
		return false, fmt.Errorf("is_ready not found")
	}
	defer fn.Close()
	result, err := fn.Call()
	if err != nil {
		return false, err
	}
	defer result.Close()
	return result.Bool()
}

// ReadMessages wraps Transport.read_messages.
// Read and parse messages from the transport.
func (w *Transport) ReadMessages() (any, error) {
	fn := w.obj.Attr("read_messages")
	if fn == nil {
		return nil, fmt.Errorf("read_messages not found")
	}
	defer fn.Close()
	result, err := fn.Call()
	if err != nil {
		return nil, err
	}
	defer result.Close()
	return result.GoValue()
}

// Write wraps Transport.write.
// Write raw data to the transport.
func (w *Transport) Write(data string) error {
	fn := w.obj.Attr("write")
	if fn == nil {
		return fmt.Errorf("write not found")
	}
	defer fn.Close()
	result, err := fn.Call(data)
	if err != nil {
		return err
	}
	result.Close()
	return nil
}

// TypeVar wraps a Python TypeVar instance.
// Type variable.
type TypeVar struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewTypeVar creates a new TypeVar instance.
func (m *Module) NewTypeVar() (*TypeVar, error) {
	cls := m.mod.Attr("TypeVar")
	if cls == nil {
		return nil, fmt.Errorf("class TypeVar not found")
	}
	defer cls.Close()
	obj, err := cls.Call()
	if err != nil {
		return nil, err
	}
	return &TypeVar{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *TypeVar) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *TypeVar) Object() *pyffi.Object {
	return w.obj
}

// UserMessage wraps a Python UserMessage instance.
// User message.
type UserMessage struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewUserMessage creates a new UserMessage instance.
func (m *Module) NewUserMessage(content any, uuid any, parentToolUseId any, toolUseResult any) (*UserMessage, error) {
	cls := m.mod.Attr("UserMessage")
	if cls == nil {
		return nil, fmt.Errorf("class UserMessage not found")
	}
	defer cls.Close()
	obj, err := cls.Call(content, uuid, parentToolUseId, toolUseResult)
	if err != nil {
		return nil, err
	}
	return &UserMessage{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *UserMessage) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *UserMessage) Object() *pyffi.Object {
	return w.obj
}

// UserPromptSubmitHookInput wraps a Python UserPromptSubmitHookInput instance.
// Input data for UserPromptSubmit hook events.
type UserPromptSubmitHookInput struct {
	obj *pyffi.Object
	rt  *pyffi.Runtime
}

// NewUserPromptSubmitHookInput creates a new UserPromptSubmitHookInput instance.
func (m *Module) NewUserPromptSubmitHookInput() (*UserPromptSubmitHookInput, error) {
	cls := m.mod.Attr("UserPromptSubmitHookInput")
	if cls == nil {
		return nil, fmt.Errorf("class UserPromptSubmitHookInput not found")
	}
	defer cls.Close()
	obj, err := cls.Call()
	if err != nil {
		return nil, err
	}
	return &UserPromptSubmitHookInput{obj: obj, rt: m.rt}, nil
}

// Close releases the underlying Python object.
func (w *UserPromptSubmitHookInput) Close() error {
	return w.obj.Close()
}

// Object returns the underlying Python object.
func (w *UserPromptSubmitHookInput) Object() *pyffi.Object {
	return w.obj
}
